..\MASM\MASM fire_1.asm
..\MASM\LINK fire_1.obj
..\MASM\MASM fire_2.asm
..\MASM\LINK fire_2.obj
..\MASM\MASM fire_4.asm
..\MASM\LINK fire_4.obj
..\MASM\MASM fire_8.asm
..\MASM\LINK fire_8.obj
..\MASM\MASM fire_16.asm
..\MASM\LINK fire_16.obj
